#SWIG Python Binding Convenient Function
FUNCTION(SWIG_PYTHON_WRAPPER
    C_LIBRARY
    C_INTERFACE
    MODULE_NAME)
    
FIND_PACKAGE(SWIG REQUIRED)
INCLUDE(${SWIG_USE_FILE})

FIND_PACKAGE(PythonLibs REQUIRED)
INCLUDE_DIRECTORIES(${PYTHON_INCLUDE_PATH})

SET(CMAKE_SWIG_FLAGS "-Wall;-threads")
SET_SOURCE_FILES_PROPERTIES(${C_INTERFACE} PROPERTIES CPLUSPLUS ON)
SET_SOURCE_FILES_PROPERTIES(${C_INTERFACE} PROPERTIES SWIG_FLAGS "-I=/usr/include -includeall")

SWIG_ADD_MODULE(${MODULE_NAME} python ${C_INTERFACE})
SWIG_LINK_LIBRARIES(${MODULE_NAME} ${PYTHON_LIBRARY} ${C_LIBRARY})

IF (CMAKE_SYSTEM_NAME STREQUAL Linux)
    SET_TARGET_PROPERTIES(_${MODULE_NAME} PROPERTIES LINK_FLAGS -Wl,-no-undefined -module -avoid-version)
ENDIF (CMAKE_SYSTEM_NAME STREQUAL Linux)

INSTALL(TARGETS _${MODULE_NAME} DESTINATION lib)
INSTALL(PROGRAMS ${CMAKE_CURRENT_BINARY_DIR}/${MODULE_NAME}.py DESTINATION py-package)

ENDFUNCTION(SWIG_PYTHON_WRAPPER)
